spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.bluebrewlab.com:3306/dbkimjusubbl
    username: kimjusubbl
    password: k5803jskim*

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Updated dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true

  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: test-pretty
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# loggint 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
scheduler:
  queueProcess:
    fixedRate: 60000 # 1분마다 실행 (밀리초 단위)
    passLimit: 30
  queueCleanup:
    fixedRate: 30000 # 30초마다 실행 (밀리초 단위)
    expirationMinutes: 10
  reservationCleanup:
    fixedRate: 60000 # 1분마다 실행 (밀리초 단위)
    expirationMinutes: 5