spring:
  application:
    name: concert-reservation
  profiles:
    active: mysql
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /concert-reservation-swagger/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  paths-to-match: /api/**
  api-docs:
    path: /concert-reservation-swagger/v3/api-docs